import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./navbar/navbar";


export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by Anlel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-primary">
        <Providers>
          <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
