import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./navbar/navbar";
import Footer from "./footer/footer";
import { ReduxProvider } from "@/redux/provider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by Anlel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className="bg-lightgray dark:bg-silver">
        <ReduxProvider>
          <ToastContainer />
          <Providers>
            <Navbar />
            {children}
          </Providers>
        <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
