import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./navbar/navbar";
import Footer from "./footer/footer";
import { ReduxProvider } from "@/redux/provider";
import { ToastContainer } from "react-toastify";
import favicon from "./favicon.ico";
import AuthProvider from "./auth/Providers";

export const metadata: Metadata = {
  title: "Otaku Store",
  description: "Generated by Anlel",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <link rel="icon" href={favicon.src} />
      </head>
      <body className="bg-lightgray dark:bg-silver">
        <AuthProvider>
          <ReduxProvider>
            <ToastContainer />
            <Providers>
              <Navbar />
              {children}
            </Providers>
            <Footer />
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
